name: General Discussion
description: Discuss something related to Lawnicons.
labels: [discussion]
body:
  - type: textarea
    id: question
    attributes:
      label: About this discussion
      description: Add the contents of your discussion here.
    validations:
      required: true
