name: General discussion
description: Discuss something related to Lawnicons.
body:
  - type: textarea
    id: question
    attributes:
      label: Description
      description: |
        **Before you start**  
        - Please attach screenshots or screen recordings so that we can understand your issue better.  
        - If you want to report a bug, it may have been fixed in [the pre-release build](https://github.com/LawnchairLauncher/lawnicons#download).  
        
    validations:
      required: true
