name: General discussion
description: Discuss something related to Lawnicons.
body:
  - type: textarea
    id: question
    attributes:
      label: Description
      description: |
        **Before you start**  
        If you want to report a bug, it may have been fixed in [the latest development build](https://github.com/LawnchairLauncher/lawnicons#download).  
        
    validations:
      required: true
