name: Update an existing icon
description: Request changing an icon if it is outdated or applied incorrectly.
labels: ["icon update"]
body:
  - type: textarea
    id: outdated-icon-list
    attributes:
      label: Icons
      description: |
        **Please specify which icon and app name need to be updated and how**
        You can find the current icon and application name in [the appfilter.xml](https://github.com/LawnchairLauncher/lawnicons/blob/develop/app/assets/appfilter.xml). For example, you found "...**drawable="ladb" name="ADB Shell" />**". The icon is [ladb](https://github.com/LawnchairLauncher/lawnicons/tree/develop/svgs/ladb.svg) and the application name is **ADB Shell**.

        **Sample response**
        Now: Twitter, [twitter.svg](https://github.com/LawnchairLauncher/lawnicons/tree/develop/svgs/)
        New: X, [fresh icon](https://cdn.cms-twdigitalassets.com/content/dam/about-twitter/x/brand-toolkit/logo-black.png.twimg.2560.png)
        
      placeholder: Tell us what should be changed and how
    validations:
      required: true
