name: Change an outdated icon
description: Request updating an icon if it is outdated or applied incorrectly.
labels: ["icon change"]
body:
  - type: textarea
    id: outdated-icon-list
    attributes:
      label: Outdated icons
      description: |
        Please specify what will change:
        
        **Old App Name**
        The [link to the outdated icon](https://github.com/LawnchairLauncher/lawnicons/tree/develop/svgs).
        ↓
        **New App Name**
        The image of the new icon.
        
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
