name: Update an existing icon
description: Request changing an icon if it is outdated or applied incorrectly.
labels: ["icon update"]
body:
  - type: textarea
    id: outdated-icon-list
    attributes:
      label: Icons
      description: |
        **Please specify for each icon**
        – The current icon and application name in Lawnicons (search in [the appfilter.xml](https://github.com/LawnchairLauncher/lawnicons/blob/develop/app/assets/appfilter.xml)).
          For example, you found **...drawable="ladb" name="ADB Shell" />**. The icon is [ladb](https://github.com/LawnchairLauncher/lawnicons/tree/develop/svgs/ladb.svg). The application name is **ADB Shell**.    
        
        – The image of the new icon and the new application name, if changed.

        **Example**
        Now
        Twitter, [twitter.svg](https://github.com/LawnchairLauncher/lawnicons/tree/develop/svgs/)
        New
        X, [fresh icon](https://cdn.cms-twdigitalassets.com/content/dam/about-twitter/x/brand-toolkit/logo-black.png.twimg.2560.png)
        
      placeholder: Tell us what should be changed and how
    validations:
      required: true
