name: Report outdated icons
description: Request to change an icon if its design is outdated.
labels: ["redesign"]
body:
  - type: markdown
    attributes:
      value: |
        #### Before you start
        If an existing icon isn't applying automatically, [create a pull request instead](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#adding-icons-and-missing-app-ids-to-lawnicons).

        #### How to find the current icon and app name  
        Search [the appfilter.xml](https://github.com/LawnchairLauncher/lawnicons/blob/develop/app/assets/appfilter.xml). In the line `drawable="..." name="..."`: `drawable` — icon name, `name` — app name.
        
        #### Sample response
        When an app's design changes, but Lawnicons still shows the old icon.  

        ```
        X (formerly Twitter)  
        Now: https://github.com/LawnchairLauncher/lawnicons/tree/develop/svgs/twitter.svg  
        New: https://cdn.cms-twdigitalassets.com/content/dam/about-twitter/x/brand-toolkit/logo-black.png.twimg.2560.png  
        ```

  - type: textarea
    id: outdated-icon-list
    attributes:
      label: Icons
      placeholder: Outdated icons
    validations:
      required: true
