name: Submit backer's pick
description: For Open Collective backers.
labels: ["pick"]

body:

  - type: markdown
    attributes:
      value: |
        An option for backers to highlight icons on our icon request dashboard. It doesn't guarantee fulfillment, but it raises the priority of the requested icons among thousands of others.
        
  - type: input
    id: oc_profile_link
    validations:
      required: true
    attributes:
      label: Open Collective profile link
      placeholder: "https://opencollective.com/your-profile"
      description: |
        To verify your backer status, please add your GitHub account to your Open Collective profile: click avatar in the top right → Settings (Info) → Social Links → Add GitHub link → Save.

  - type: upload
    id: icon_request_file
    validations:
      required: true
    attributes:
      label: Icon request file
      description: |
        Create an icon request file: Open Lawnicons → Tap "Request icons" → Select icons → Share or save file.
