name: Support my app
description: For apps with 10,000+ users.
title: "App name: "
labels: ["dev request"]

body:
  - type: checkboxes
    id: prerequisities
    attributes:
      label: Prerequisities
      options:
        - label: The app is trusted by 10,000+ unique users.
          required: true

  - type: input
    id: applink
    validations:
      required: true
    attributes:
      label: Applicaton link
      description: |
       To verify your developer status, please provide a public link to your application (GitHub, Google Play, etc).

  - type: textarea
    id: components
    validations:
      required: true
    attributes:
      label: Components
      description: |
        Please specify which app components the icon should be linked with (package/activity).

  - type: textarea
    id: icon
    validations:
      required: true
    attributes:
      label: Icon image
      description: |
        A high-quality image of the current icon will simplify the process.
