name: Close stale PRs

on:
  schedule:
    - cron: 0 0 1-31 * *
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-pr-message: This pull request is now stale. Please resolve the remaining issues before it closes in 4 days, or comment if you are still on it.
          days-before-pr-stale: 30
          days-before-pr-close: 4
          days-before-issue-stale: -1
          exempt-draft-pr: true
          operations-per-run: 500
          labels-to-remove-when-unstale: stale
