name: Crowdin Synchronization

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    name: Synchronize with Crowdin
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - name: Sync Translations
        uses: crowdin/github-action@v2
        with:
          upload_translations: false
          upload_sources: true
          download_translations: true
          localization_branch_name: i18n
          create_pull_request: true
          base_url: 'https://lawnchair.crowdin.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
