name: first-interaction

on:
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  check_for_first_interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thanks for your interest in contributing to Lawnicons! If you are not contributing icons, please disregard the below.

            Ensure that the size of your icons, their line thicknesses, and their corner radius match the [Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#icon-guidelines).
            If something is wrong with your icons, please correct them and update the PR.

            If everything is according to the guidelines, the reviewers will quickly accept the PR. Otherwise, you will be asked to fix the icons.
