name: Icon Linter

on:
  # Lint icons after commenting checklist
  workflow_run:
    workflows: [ "Comment icon checklist" ]
    types: [ completed ]

jobs:
  lint:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to compare with base branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Run Linter and Post Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: python .github/scripts/bot_orchestrator.py
